### ISSUE TITLE
The intent site example need correction. the config is of type list.

### ISSUE THREAD

**Issue by DNACENSolutions** [cisco-en-programmability/dnacenter-ansible#105]
**Prerequisites**
* [ Y] Have you tested the operation in the API directly?
* [ Y] Do you have the latest Ansible collection version?
* [ Y] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacenter-ansible/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**
The site esmaple give need to have config as list but example gives as dict which causes confusion in usages and needs fixing.

Current one:
```yml
EXAMPLES = r"""
- name: Create a new building site
  cisco.dnac.site_intent:
    dnac_host: "{{dnac_host}}"
    dnac_username: "{{dnac_username}}"
    dnac_password: "{{dnac_password}}"
    dnac_verify: "{{dnac_verify}}"
    dnac_port: "{{dnac_port}}"
    dnac_version: "{{dnac_version}}"
    dnac_debug: "{{dnac_debug}}"
    dnac_log: "{{dnac_log}}"
    config:
        site:
          building:
            address: string
            latitude: 0
            longitude: 0
            name: string
            parentName: string
        type: string
"""


Expected to be:
EXAMPLES = r"""
- name: Create a new building site
  cisco.dnac.site_intent:
    dnac_host: "{{dnac_host}}"
    dnac_username: "{{dnac_username}}"
    dnac_password: "{{dnac_password}}"
    dnac_verify: "{{dnac_verify}}"
    dnac_port: "{{dnac_port}}"
    dnac_version: "{{dnac_version}}"
    dnac_debug: "{{dnac_debug}}"
    dnac_log: "{{dnac_log}}"
    config:
    -  site:
          building:
            address: string
            latitude: 0
            longitude: 0
            name: string
            parentName: string
        type: string
"""

Working Sample:
  tasks:
    - name: Create Sites
      cisco.dnac.site_intent:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        state: merged
        config:
        - site:
            building:
              address: null
              latitude: "12.933971097851867"
              longitude: "80.24676818041894"
              name: bgl11
              parentName: Global/SAN JOSE
          type: building
====
```

**Expected behavior**

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 
* Ansible Version:
* Collection version:
* OS Version: 

**Additional context**
