### ISSUE TITLE
Cannot add building when using vars yaml file due to latitude value being passed to sdk as string

### ISSUE THREAD

**Issue by paulbauer1** [cisco-en-programmability/dnacenter-ansible#111]
**Prerequisites**
* [Yes ] Have you tested the operation in the API directly?
* [ Yes] Do you have the latest Ansible collection version?
* [ Yes] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacenter-ansible/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**
When creating a building and looping through a yml file with building information an error is returned from the dnacentersdk stating that the latitude value must be a number. The latitude value in the yml file is a number and I have tried to cast the value in the ansible task as well. It is always sent as a string to the sdk. If I hard code a number into the latitude and longitude fields the task works as expected. Below is the task, the yaml data and the error. Maybe this is more of an sdk error where the sdk should be taking in the string and converting it or just passing the string to the API. If I try creating a building in the developer toolkit area (API call) on my dnac server the response body can contain a number with or withour quotes and the building will be created. Same with postman.

Ansible task
```
# DNA Center Site Creation
- name: Create building
  cisco.dnac.site_create:
    dnac_host: "{{ ansible_host }}"
    dnac_username: "{{ username }}"
    dnac_password: "{{ password }}"
    dnac_verify: false
    dnac_port: 443
    dnac_version: "2.3.3.0"
    site:
      building:
        address: "{{ item.address }}"
        country: "{{ item.country }}"
        latitude: "{{ (item.latitude | float) }}"
        longitude: "{{ (item.longitude | float) }}" 
        name: "{{ [item.name](http://item.name/) }}"
        parentName: "{{ item.parent_name }}"
    type: "{{ item.site_type }}"
  loop: "{{ sites }}"
  when:  item.site_type == 'building'
```

YAML Data 
```
# vars file for dnac-create-site-hierarchy
sites:
  # North America
  - name: "US"
    site_type: "area"
    parent_name: "Global"
  - name: "Big Campus"
    site_type: "area"
    parent_name: "Global/US"
  - name: "Big_bldg"
    site_type: "building"
    address: "2222 Big Dr."
    country: "United States"
    latitude: 44.22222
    longitude: -111.11111
    parent_name: "Global/US/Big Campus"
```

Error Message returned from the Cisco DNAC SDK which is required for the Cisco.DNAC Ansible Module

```
raise MalformedRequest(
dnacentersdk.exceptions.MalformedRequest: {'type': 'building', 'site': {'building': {'address': '2222 Big Dr.', 'country': 'United States', 'latitude': '44.22222', 'longitude': '-111.11111', 'name': 'Big_bldg', 'parentName': 'Global/US/Big Campus'}}} is invalid. Reason: data.site.building.latitude must be number
failed: [dna-center-lab] (item={'name': 'Big_bldg', 'site_type': 'building', 'address': '2222 Big Dr.', 'country': 'United States', 'latitude': 44.22222, 'longitude': -111.11111, 'parent_name': 'Global/US/Big Campus'}) => {
    "ansible_loop_var": "item",
    "item": {
        "address": "2222 Big Dr.",
        "country": "United States",
        "latitude": 44.22222,
        "longitude": -111.11111,
        "name": "Big_bldg",
        "parent_name": "Global/US/Big Campus",
        "site_type": "building"
    },
    "msg": "An error occured when executing operation. The error was: {'type': 'building', 'site': {'building': {'address': '2222 Big Dr.', 'country': 'United States', 'latitude': '44.22222', 'longitude': '-111.11111', 'name': 'Big_bldg', 'parentName': 'Global/US/Big Campus'}}} is invalid. Reason: data.site.building.latitude must be number"
}
```

**Expected behavior**
The ansible call to the sdk should work as the API does. Accept a string or number value if th eunderlying value is a number.

**Screenshots**
Screenshot of API call with and without quotes on server and postman
![Screenshot 2023-08-18 at 12 40 55 PM](https://github.com/cisco-en-programmability/dnacenter-ansible/assets/10010378/c6ad1f98-e502-4dd6-b736-3ed836f41e4c)
![Screenshot 2023-08-18 at 12 41 45 PM](https://github.com/cisco-en-programmability/dnacenter-ansible/assets/10010378/a26ad529-bce1-4566-9b85-9abb5f617f1f)
![Screenshot 2023-08-18 at 1 06 55 PM](https://github.com/cisco-en-programmability/dnacenter-ansible/assets/10010378/f1a997bc-57ae-402a-ad56-edd6f77ef319)
![Screenshot 2023-08-18 at 1 01 56 PM](https://github.com/cisco-en-programmability/dnacenter-ansible/assets/10010378/43030660-a00f-46ea-8e33-cac4a544abe0)

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 2.3.3.7-72328
* Ansible Version: core 2.15.3
* Collection version: 6.7.3 
* OS Version: 3.9.17-bullseye

**Additional context**
