### ISSUE TITLE
sda_layer3_virtual_networks_v1 PUT instead of POST

### ISSUE THREAD

**Issue by WouterDePrins** [cisco-en-programmability/dnacenter-ansible#221]
**Name of the module**
cisco.dnac.sda_layer3_virtual_networks_v1

**Describe the bug**
If you want to create a VN (without specifying the 'id'), Ansible is initiating a 'PUT' request.
The error output states that 'id is a required field'.

**Expected behavior**
I expect a 'POST' request as the 'id' is not specified and a new VN is going to be created.

**Debug**
```
        payload:
        - fabricIds:
          - "e3327bd5-e30b-40be-92ac-d6235f35a29b"
          virtualNetworkName: "Test2"
```

URL: https://10.10.10.10:443/dna/intent/api/v1/sda/layer3VirtualNetworks
Method: **PUT**
"detail": "Layer 3 Virtual Network Update failed for Test2 in SDA Fabric, id is a required field."

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 2.3.7.7-70047
* Ansible Version: core 2.18.1
* Collection version: latest
* OS Version: MacOS 15.2
