### ISSUE TITLE
site_workflow_manager - floor_number value of "0" not allowed

### ISSUE THREAD

**Issue by schroppae** [cisco-en-programmability/dnacenter-ansible#234]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Ansible collection version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacenter-ansible/tree/main#compatibility-matrix) before opening an issue.

**Name of the module**
site_workflow_manager

**Describe the bug**
The module site_workflow_manager is not accepting the value 0 (zero) as a floor number.
The shown error message is:
`Missing or invalid parameters in playbook config: ''floor_number' should not be None or empty.'`

Task:
```YAML
    - name: Create sites from design_sites config
      cisco.dnac.site_workflow_manager:
        <<: *dnac_login
        dnac_version: "{{ dnac_version }}"
        dnac_verify: "{{ dnac_verify }}"
        state: "{{state}}"
        config: "{{design_sites}}"
      register: site_output
      when: design_sites is defined and design_sites | length > 0
```

var file input:
```YAML
design_sites:
  - site:
      floor:
        name: "00"
        parent_name: Global/Germany/Berlin/Sample
        rfModel: Cubes And Walled Offices
        width: 100.00
        length: 100.00
        height: 10.00
        floor_number: 0
```

I think this is because the check in line [1252](https://github.com/cisco-en-programmability/dnacenter-ansible/blob/b507a8a21ed73081c60d7f503a4d7084437f640a/plugins/modules/site_workflow_manager.py#L1252) `if floor_number:` will resolve as False for `floor_number = 0` and therefore going directly to the else block in line [1257](https://github.com/cisco-en-programmability/dnacenter-ansible/blob/b507a8a21ed73081c60d7f503a4d7084437f640a/plugins/modules/site_workflow_manager.py#L1257) as indicated by the debug logs.

**Expected behavior**
The Ansible module site_workflow_manager should accept a value of "0" for floor_number as it is in the valid range from -200 to 200.

**Screenshots**
<img width="560" alt="Image" src="https://github.com/user-attachments/assets/1721fdfa-bb25-4a20-9ead-30958fd8f07b" />

**Debug**
```
02-10-2025 14:10:55 INFO  Site: validate_input: 495: Configuration details found in the playbook: [**removed for privacy**] 
02-10-2025 14:10:55 INFO  Site: validate_input: 515: Successfully validated playbook config params: [**removed for privacy**] 
02-10-2025 14:10:55 INFO  Site: validate_site_input_data: 1317: Default value assigned for units_of_measure: feet. 
02-10-2025 14:10:55 INFO  Site: validate_site_input_data: 1317: Default value assigned for units_of_measure: feet. 
02-10-2025 14:10:55 ERROR  Site: validate_site_input_data: 1259: Missing 'floor_number' in floor entry. 
02-10-2025 14:10:55 INFO  Site: validate_site_input_data: 1317: Default value assigned for units_of_measure: feet. 
02-10-2025 14:10:55 ERROR  Site: validate_site_input_data: 1335: Missing or invalid parameters in playbook config: ''floor_number' should not be None or empty.'  
```

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 2.3.7.7-70047
* Ansible Version: ansible [core 2.17.8]
* Collection version: cisco.dnac 6.25.0
* OS Version: Ubuntu 22.04.4

**Additional context**
