### ISSUE TITLE
An error occured when executing operation. The error was: [400] Bad Request - NCOB01291: Configuration and Image information are required

### ISSUE THREAD

**Issue by beye91** [cisco-en-programmability/dnacenter-ansible#36]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest Ansible collection version?

**Describe the bug**
Hey guys, while using this module it is only possible to use three variables (deviceID,siteID,type).

My playbook looks like this:
```
   - name: Claim device to a site
      cisco.dnac.pnp_device_claim_to_site:
        dnac_host: "{{ dnac_host }}"
        dnac_port: "{{ dnac_port }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_debug: "{{ dnac_debug }}"
        deviceId: "{{ device_id }}"
        siteId: "{{ site_id }}"
        type: "Default"
```

**When I execute the playbook it creates the following error:** 
`An error occured when executing operation. The error was: [400] Bad Request - NCOB01291: Configuration and Image information are required`

Defining the imageId and configId is not possible because of the _check_argspec function in the code. 

**When defining the missing variables I get the following error:**
`['configId, imageId. Supported parameters include: validate_response_schema, dnac_username (user), type, deviceId, dnac_password, dnac_debug, dnac_version, dnac_verify, dnac_host, siteId, dnac_port.']`

**Expected behavior**

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.
```
{
   "siteId":"'${SITEID}'",
   "deviceId":"'${DEVICEID}'",
   "hostname":"'${hostname}'",
   "type":"Default",
   "imageInfo":{
      "imageId":"'${IMAGEID}'",
      "skip":false
   },
   "configInfo":{
      "configId":"'${TEMPLATEID}'",
      "configParameters":[
         {
            "key":"hostname",
            "value":"'${hostname}'"
         },
         {
            "key":"asn",
            "value":"'${asn}'"
         }
      ]
   }
} 

```
**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 2.2.2.8
* Ansible Version: 2.12.1
* Collection version: 3.2.3
* OS Version: MacOS

**Additional context**
Please add the additional variables to the Ansible module in order to submit a successful API call.
