### ISSUE TITLE
Unable to tag templates

### ISSUE THREAD

**Issue by beye91** [cisco-en-programmability/dnacenter-ansible#40]
**Prerequisites**
* [ X] Have you tested the operation in the API directly?
* [ X] Do you have the latest Ansible collection version?

**Describe the bug**
While trying to tag a template the SDK is creating an error:

**dnacentersdk.exceptions.MalformedRequest: {'memberToTags': [{'key': 'e64d42a9-3db7-456b-8486-58afd0373bd1:[17d26e24-7796-4faf-9be0-bd0a642aa846]'}], 'memberType': 'template'} is invalid. Reason: data.memberToTags[0].key must be array**

The playbook I used looks like this:
`      cisco.dnac.tag_membership:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_debug: "{{dnac_debug}}"
        memberToTags:
          - key: "e64d42a9-3db7-456b-8486-58afd0373bd1:[17d26e24-7796-4faf-9be0-bd0a642aa846]"
        memberType: template
      register: tag_membership_result
      tags: 
        - tag`

The documentation describes the memberToTags as a list.

**Expected behavior**
Datatype should be changed.

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 2.2.2.6
* Ansible Version: 3.2.3
* Collection version: 2.3.3
* OS Version: MacOS

**Comment by bvargasre** [comment]
Greetings, let's review the issue.
I have a couple of questions:
First, in the 'Collection version' of cisco.dnac what are you using?
Because it seems that you are providing us with the value of the dnac_version argument. 
You can find out which one is with `ansible-galaxy collection list | grep "cisco.dnac"`
Can you attach the request body to the API you are using?

**Comment by beye91** [comment]
Hey @bvargasre , I am using version "cisco.dnac 3.2.3"

The wrong call from the playbook:
 {'memberToTags': [{'key': 'e64d42a9-3db7-456b-8486-58afd0373bd1:[17d26e24-7796-4faf-9be0-bd0a642aa846]'}], 'memberType': 'template'}

This is how it should look like:
{"memberType":"template","memberToTags":{"e64d42a9-3db7-456b-8486-58afd0373bd1":["17d26e24-7796-4faf-9be0-bd0a642aa846"]}}

**Comment by beye91** [comment]
Let me know if anything else is needed.

**Comment by bvargasre** [comment]
Greetings @beye91 ,  already solved the problem, if you can update the version of ansible version 3.2.3 to 3.3.0, besides it would be good to add `validate_response_schema: False` in the playbook to avoid MalformedRequest
For example:
```
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      validate_response_schema: False
      ...
```
If the problem still appears or a new one appears, please let us know and we will be happy to fix it.

**Comment by beye91** [comment]
@bvargasre I experienced issues to set the template ID as a variable:

`      cisco.dnac.tag_membership:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_debug: "{{dnac_debug}}"
        validate_response_schema: False
        memberToTags:
        - "{{ template_id }}" :
          - "{{ tag_id }}"
        memberType: template`

It wont set the template_id as a variable. Do you have an idea?

**Comment by wastorga** [comment]
Hi, @beye91.

I was able to find some useful links regarding creating/manipulating objects in Ansible.

- [Official documentation](https://docs.ansible.com/ansible/latest/user_guide/complex_data_manipulation.html#create-dictionary-from-list)
- [Blog tutorial](https://www.middlewareinventory.com/blog/ansible-dict/)

**Comment by wastorga** [comment]
With that information, I was able to create the following example.

```yaml
- hosts: dnac_servers
  vars_files:
    - credentials.yml
  gather_facts: no
  vars:
    dnac_login: &dnac_login
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_version: "{{dnac_version}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_debug: "{{dnac_debug}}"
  tasks:
    - name: Create memberToTags dictionary
      vars:
        templateID: "8bf887f3-7cc2-4bd2-9407-df0fe6b7f63a"
        tagID: "68f7ebd1-81fc-4099-944c-ac38ef6455a5"
      set_fact:
        memberToTags: "{{ memberToTags | default([]) + [{ item.TemplateID : item.TagID}] }}"
      with_items:
        - { "TemplateID": "{{templateID}}", "TagID": ["{{tagID}}"] }

    - name: Display the Dictionary
      debug: var=memberToTags

    - name: Update tag_membership
      cisco.dnac.tag_membership:
        <<: *dnac_login
        validate_response_schema: False
        memberToTags: "{{ memberToTags | list }}"
        memberType: template
      register: result
```
