### ISSUE TITLE
Creating Reports is not successful (cisco.dnac.reports)

### ISSUE THREAD

**Issue by beye91** [cisco-en-programmability/dnacenter-ansible#57]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest Ansible collection version?

**Describe the bug**
Ansible play:
```
    - name: Create
      cisco.dnac.reports:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_debug: "{{dnac_debug}}"
        state: present
        deliveries:
        -
        name: "AP-ANSIBLE"
        schedule: {"type": "SCHEDULE_NOW","dateTime":1648380084211}
        tags: 
        - 
        view:
          fieldGroups:
          - fieldGroupDisplayName: "AP Detail By AP"
            fieldGroupName: "apDetailByAP"
            fields:
            - displayName: "AP MAC Address"
              name: "macAddress"
            - displayName: "Up Time"
              name: "upTime"
          filters:
          - displayName: "Location"
            name: "Location"
            type: "MULTI_SELECT_TREE"
            value: {"value": "sample-global-site-id", "displayValue": "Global"}
          - displayName: "Time Range"
            name: "TimeRange"
            type: "TIME_RANGE"
            value: {"timeRangeOption":"LAST_3_HOURS","startDateTime":0,"endDateTime":0}
          format:
            formatType: "CSV"
            name: "CSV"
          name: AP
        viewGroupId: "c8bfe5c9-4941-4251-8bf5-0fb643e90816"
        viewGroupVersion: "2.0.0"
      register: result
```

Error:
`{'tags': [None], 'deliveries': [None], 'name': 'AP-ANSIBLE', 'schedule': {'type': 'SCHEDULE_NOW', 'dateTime': 1648380084211}, 'view': {'fieldGroups': [{'fieldGroupDisplayName': 'AP Detail By AP', 'fieldGroupName': 'apDetailByAP', 'fields': [{'displayName': 'AP MAC Address', 'name': 'macAddress'}, {'displayName': 'Up Time', 'name': 'upTime'}]}], 'filters': [{'displayName': 'Location', 'name': 'Location', 'type': 'MULTI_SELECT_TREE', 'value': {'value': 'sample-global-site-id', 'displayValue': 'Global'}}, {'displayName': 'Time Range', 'name': 'TimeRange', 'type': 'TIME_RANGE', 'value': {'timeRangeOption': 'LAST_3_HOURS', 'startDateTime': 0, 'endDateTime': 0}}], 'format': {'formatType': 'CSV', 'name': 'CSV'}, 'name': 'AP'}, 'viewGroupId': 'c8bfe5c9-4941-4251-8bf5-0fb643e90816', 'viewGroupVersion': '2.0.0'}`

How the data should look like:
```
{
   "tags":[
       
   ],
   "deliveries":[
       
   ],
   "name":"AP-ANSIBLE",
   "schedule":{
      "type":"SCHEDULE_NOW",
      "dateTime":1648380084211
   },
   "view":{
      "fieldGroups":[
         {
            "fieldGroupDisplayName":"AP Detail By AP",
            "fieldGroupName":"apDetailByAP",
            "fields":[
               {
                  "displayName":"AP MAC Address",
                  "name":"macAddress"
               },
               {
                  "displayName":"Up Time",
                  "name":"upTime"
               }
            ]
         }
      ],
      "filters":[
         {
            "displayName":"Location",
            "name":"Location",
            "type":"MULTI_SELECT_TREE",
            "value":[
                {
               "value":"sample-global-site-id",
               "displayValue":"Global"
            }
        ]
         },
         {
            "displayName":"Time Range",
            "name":"TimeRange",
            "type":"TIME_RANGE",
            "value":{
               "timeRangeOption":"LAST_3_HOURS",
               "startDateTime":0,
               "endDateTime":0
            }
         }
      ],
      "format":{
         "formatType":"CSV",
         "name":"CSV"
      },
      "name":"AP"
   },
   "viewGroupId":"c8bfe5c9-4941-4251-8bf5-0fb643e90816",
   "viewGroupVersion":"2.0.0"
}
```

**Environment (please complete the following information):**
Package            Version
------------------ ---------
ansible            5.5.0
ansible-core       2.12.3
certifi            2021.10.8
cffi               1.15.0
charset-normalizer 2.0.12
cryptography       36.0.2
dnacentersdk       2.4.7
fastjsonschema     2.15.3
future             0.18.2
idna               3.3
Jinja2             3.0.3
MarkupSafe         2.1.1
packaging          21.3
pip                21.3.1
pycparser          2.21
pyparsing          3.0.7
PyYAML             6.0
requests           2.27.1
requests-toolbelt  0.9.1
resolvelib         0.5.4
setuptools         60.5.0
urllib3            1.26.9
