### ISSUE TITLE
File Info module reports file created, but doesn't create the file

### ISSUE THREAD

**Issue by miarond** [cisco-en-programmability/dnacenter-ansible#62]
**Prerequisites**
* [x] Have you tested the operation in the API directly?  **Yes**
* [x] Do you have the latest Ansible collection version? **Yes**

**Describe the bug**
The module `cisco.dnac.file_info` will perform an API call to the DNA Center controller and request the download of a file by it's File ID.  The resulting response reports the filename to be created, as well as the path where the file will be saved, but the file is never actually written to disk at the location specified.

**Expected behavior**
The DNA Center SDK package exhibits the same behavior however, the resulting output is stored in a `DownloadResponse` object container.  It makes sense that the Ansible module would behave this way as well however, if the output response shows the filename and the file path, there should be a mechanism added to the module that actually *creates* this file as well.

**Screenshots**
Ansible:
![image](https://user-images.githubusercontent.com/48371008/174163987-71318839-f497-4fd8-926f-32dcb94ab4ec.png)

DNA Center Python SDK:
![image](https://user-images.githubusercontent.com/48371008/174164114-57759960-f00c-4816-a2d0-62816f2e4fee.png)

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 2.2.3.4
* Ansible Version: 2.12.15
* Collection version:  6.4.0
* OS Version: MacOS 12.4

**Additional context**
I have tested this using the DevNet Always-On DNA Center Sandbox at https://sandboxdnac.cisco.com

**Comment by bvargasre** [comment]
Hi @miarond could you pass the playbook you used for the test.

**Comment by miarond** [comment]
[Archive.zip](https://github.com/cisco-en-programmability/dnacenter-ansible/files/8931523/Archive.zip)
@bvargasre Here is the playbook, vars file, and task file that I used.  I've since modified the task file to work around the problem I reported, but if you remove or comment out the final "Saving File..." task, you'll get the results I reported.

**Comment by bvargasre** [comment]
Checking your `cisco.dnac.file_info` playbook, there are some headers parameters that are missing:`saveFile`, `dirPath` and `filename`
Example:
``` yml
- name: Downloading File...
  cisco.dnac.file_info:
    dnac_host: "{{dnac_host}}"
    dnac_username: "{{dnac_username}}"
    dnac_password: "{{dnac_password}}"
    dnac_verify: "{{dnac_verify}}"
    dnac_port: "{{dnac_port}}"
    dnac_version: "{{dnac_version}}"
    dnac_debug: "{{dnac_debug}}"
    fileId: "{{task_status.dnac_response.response.progress[11:-2]}}"
    saveFile: true
    dirPath: /path/
    filename: the file name
  register: file_status
```
Try it, and let know us if is working for you.

---
**Note:**

dirPath is the abosulete path of the directory where the file will be downloaded, if the directory does not exist the file will be saved at the level where the playbook was executed. 

---
