### ISSUE TITLE
Issue deleting a discovery job with the Ansible "cisco.dnac.discovery" module

### ISSUE THREAD

**Issue by ledelmann** [cisco-en-programmability/dnacenter-ansible#65]
**Prerequisites**
* [ ] Have you tested the operation in the API directly?
* [X] Do you have the latest Ansible collection version?

**Describe the bug**
I tried to delete a device discovery job with the Ansible module "cisco.dnac.discovery", but I received the following output and the discovery job was not deleted.

The task in the playbook is really simple:
```
...
    - name: "Task: Delete discovery job"
      cisco.dnac.discovery:
        <<: *dnac_opts
        name: "DNAC_DISC_JOB"
        state: absent
      register: delete_discovery_result
...
```

Output:

```
ok: [...] => {
    "msg": {
        "changed": false,
        "dnac_response": null,
        "failed": false,
        "result": "Object already absent"
    }
}

```

**Expected behavior**
Discovery job should be deleted.

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 2.3.3.0-70399
* Ansible Version:  2.12.0b1
* Collection version: 6.5.0
* OS Version: Ubuntu 20.04.4 LTS

**Comment by ledelmann** [comment]
Hi @bvargasre,

I think the SDK does not support "delete_discovery_by_name" and therefor it's also not available in the Ansible discovery module. The delete task works when I use the discovery ID in the playbook. The Method "get_object_by_name" does not make sense in this case.


```
discovery.py:
def delete(self):
    id = self.new_object.get("id")
    name = self.new_object.get("name")
    result = None
    if not id:
        prev_obj_name = self.get_object_by_name(name)
        id_ = None
        if prev_obj_name:
            id_ = prev_obj_name.get("id")
        if id_:
            self.new_object.update(dict(id=id_))
    result = self.dnac.exec(
        family="discovery",
        function="delete_discovery_by_id",
        params=self.delete_by_id_params(),
    )
    return result
		

def get_object_by_name(self, name):
    result = None
    # NOTE: Does not have a get by name method or it is in another action
    # NOTE: Does not have get all
    return result

```

Regards,

Lukas

**Comment by bvargasre** [comment]
Hi @ledelmann you are right, the discovery does not have a get_discovery_by_name, but you can use the other modules to get the discovery_id as in this example:

```yml
tasks:
  - name: Get all Discovery Range
    cisco.dnac.discovery_range_info:
      <<: *dnac_login
      startIndex: 1
      recordsToReturn: 500
    register: result_discovery_range_info

  - name: Get discovery id
    ansible.builtin.set_fact:
      discovery_id: "{{ item.id }}"
    with_items: "{{ result_discovery_range_info.dnac_response.response }}"
    when:
      - result_discovery_range_info.dnac_response is defined
      - result_discovery_range_info.dnac_response.response is defined
      - item.name == "{{ discovery_name }}" #Here you pass the discovery_name

  - name: Delete discovery job"
    cisco.dnac.discovery:
      <<: *dnac_login
      id: "{{discovery_id }}"
      state: absent
    register: delete_discovery_result

  - name: Show result
    ansible.builtin.debug:
      msg: "{{ delete_discovery_result }}"
```
---
**Note:**

if you have more than 500 Discovery you have to change the index because in the `Get all Discovery Range` it can only return a maximum of 500 so in the `startIndex` you have to change it from 1 to 500 to bring the next 500.

---
