### ISSUE TITLE
cisco.dnac.client_enrichment_details: Provided arguments do not comply with the function schema

### ISSUE THREAD

**Issue by 020003** [cisco-en-programmability/dnacenter-ansible#7]
Hi,

I tried to use the client_enrichment_details module but I was not succesful.
The error message I recieve is:

> "msg": "Provided arguments do not comply with the function schema",

The example in the module documentation is also not really helping me getting this thing to work :) .
It's just mentioning headers, so I looked them up in the api documentation and added them. 
```
- name: get_client_enrichment_details
  cisco.dnac.client_enrichment_details:
    state: query  # required
    headers:  # required
  register: nm_get_client_enrichment_details
```

Following playbook was used.
```
- name: Play 1 Query DNAC by User
  hosts: all
  connection: local


  tasks:



   - name: get_client_enrichment_details
     cisco.dnac.client_enrichment_details:
       dnac_host: "{{ inventory_hostname }}"
       dnac_username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
       dnac_password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
       dnac_verify: false
       state: query  # required
       headers: 
           entity_type: "network_user_id"
           entity_value: "{{ userId }}" 
     register: qResult

```
