### ISSUE TITLE
Error couldn't resolve module/action 

### ISSUE THREAD

**Issue by ptrckstephenson** [cisco-en-programmability/dnacenter-ansible#9]
It appears that a module is not resolving properly. Below is the yaml file used to test this module:
```
---
- hosts:
  - localhost
  vars_files:
    - credentials.yml
    - vars.yml
  gather_facts: no
  tasks:
  - name: get_discoveries_by_range
    cisco.dnac.discovery_range_info:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      startIndex: 1
      recordsToReturn: 4
    register: discovery_list
```
The exact error message is 

```

ERROR! couldn't resolve module/action 'cisco.dnac.discovery_range_info'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/.ansible/collections/ansible_collections/cisco/dnac/playbooks/get_discovery_by_id': line 9, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
  - name: get_discoveries_by_range
    ^ here
```

I tested a similar discovery module in attempt to get the output I was looking for and cisco.dnac.discovery was working correctly:

```
---
- hosts:
  - localhost
  vars_files:
    - credentials.yml
    - vars.yml
  gather_facts: no
  tasks:
  - name: get_discovery_by_id
    cisco.dnac.discovery:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      state: query  # required
      id: ''
      validate_response_schema: False
    register: nm_get_discovery_by_id

root@ubuntu:~/.ansible/collections/ansible_collections/cisco/dnac/playbooks# ansible-playbook get_discovery_by_id
[WARNING]: running playbook inside collection cisco.dnac
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] *******************************************************************************************************************************************************************************************************************************************************

TASK [get_discovery_by_id] *********************************************************************************************************************************************************************************************************************************************
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host '198.18.129.100'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
ok: [localhost]

PLAY RECAP *************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```

Here is versioning info for reference:

```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
```

I validated the YAML files to ensure syntax. It appears that the ```_``` is causing issues with the module path.
