### ISSUE TITLE
template_intent module does not allow documented values for language parameter

### ISSUE THREAD

**Issue by chanhale** [cisco-en-programmability/dnacenter-ansible#91]
dna center Version:  2.3.3.5 & 2.3.4.0
cisco.dnac collection version 6.6.3
dnacentersdk version 2.5.6
ansible version 2.14.2

**Describe the bug**
cisco.dnac.template_intent requires a parameter called "language".  According to the module docs and the DNAC API docs the allowed values are "JINJA" or "VELOCITY".   The module does not accept these and will only accept "jinja" or "velocity".  

**Expected behavior**
The language argument should accept "JINJA" or "VELOCITY" as per the documentation & DNAC or the documentation should be changed to specify that lowercase "jinja" or "velocity" should be used.

This was tested with the following Playbook:
```
- hosts: localhost
  gather_facts: no
  connection: local
  vars_files: 
    - site_details_1.yml
  vars:
    dnac_conn: &dnac_conn
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_debug: "{{dnac_debug}}"   
 
  tasks:
        
    - name: Create Template in Project
      cisco.dnac.template_intent:
        <<: *dnac_conn
        config:
          - templateName: "Pod1Description"
            softwareType: "IOS"
            softwareVariant: "XE"
            projectName: "Pod1Project"
            language: "JINJA"
            templateContent: "{{templatecontents}}"
            deviceTypes:
            - productFamily: "Switches and Hubs"   
```
When I run this playbook, the response is:

```
PLAY [localhost] **********************************************************************************************************************************

TASK [Create Template in Project] **********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Invalid parameters in playbook: JINJA : Invalid choice provided"}

PLAY RECAP **********************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
If I change "JINJA" to "jinja" it will be accepted.

I tested this using the dnacentersdk configuration_templates.create_template with the language value "JINJA" and it does work:

```
dnacApi.configuration_templates.create_template(project_id=theprojectid, deviceTypes=deviceType, softwareType="IOS", softwareVariant="XE", name="Pod1Template", templateContent=template_text, language="JINJA")

```
